const { str } = require("./env");

const DEFAULT_AI_PROVIDER = "openai";
const DEFAULT_AI_MODEL = "gpt-4.1-mini";
const AI_PLATFORM_FALLBACK_PROVIDERS = [];

const LLM_GLOBAL_RETRY_BUDGET = 100;
const LLM_RETRY_WINDOW_MS = 60_000;
const LLM_CIRCUIT_BREAKER_THRESHOLD = 10;
const LLM_CIRCUIT_BREAKER_COOLDOWN_MS = 30_000;

const HEALTH_CHECK_TIMEOUT_MS = 20_000;
const LOCAL_HEALTH_CHECK_TIMEOUT_MS = 5_000;
const RUNTIME_GENERATION_TIMEOUT_MS = 45_000;
const RUNTIME_EMAIL_TIMEOUT_MS = 10_000;
const HEALTH_CHECK_CACHE_TTL_MS = 60_000;

const LLM_MODEL = DEFAULT_AI_MODEL;
const LLM_TIMEOUT_MS = RUNTIME_GENERATION_TIMEOUT_MS;
const LLM_MAX_ATTEMPTS = 3;
const LLM_RETRY_BASE_DELAY_MS = 750;
const MAX_LLM_INPUT_CHARS = 15_000;
const MAX_STORAGE_TEXT_CHARS = 15_000;
const JOB_POLL_INTERVAL_MS = 2_000;
const JOB_REGISTRY_TTL_MS = 60 * 60 * 1000;

const DEFAULT_MODELS = {
  openai: "gpt-4.1-mini",
  anthropic: "claude-3-5-sonnet-20241022",
  gemini: "gemini-1.5-flash",
};

module.exports = {
  openaiApiKey: str("OPENAI_API_KEY", null),
  DEFAULT_AI_PROVIDER,
  DEFAULT_AI_MODEL,
  AI_PLATFORM_FALLBACK_PROVIDERS,
  DEFAULT_MODELS,
  LLM_GLOBAL_RETRY_BUDGET,
  LLM_RETRY_WINDOW_MS,
  LLM_CIRCUIT_BREAKER_THRESHOLD,
  LLM_CIRCUIT_BREAKER_COOLDOWN_MS,
  HEALTH_CHECK_TIMEOUT_MS,
  LOCAL_HEALTH_CHECK_TIMEOUT_MS,
  RUNTIME_GENERATION_TIMEOUT_MS,
  RUNTIME_EMAIL_TIMEOUT_MS,
  HEALTH_CHECK_CACHE_TTL_MS,
  LLM_MODEL,
  LLM_TIMEOUT_MS,
  LLM_MAX_ATTEMPTS,
  LLM_RETRY_BASE_DELAY_MS,
  MAX_LLM_INPUT_CHARS,
  MAX_STORAGE_TEXT_CHARS,
  JOB_POLL_INTERVAL_MS,
  JOB_REGISTRY_TTL_MS,
};
