/** @deprecated Import from src/config or src/config/ai.config */
const ai = require("./ai.config");
module.exports = {
  HEALTH_CHECK_TIMEOUT_MS: ai.HEALTH_CHECK_TIMEOUT_MS,
  LOCAL_HEALTH_CHECK_TIMEOUT_MS: ai.LOCAL_HEALTH_CHECK_TIMEOUT_MS,
  RUNTIME_GENERATION_TIMEOUT_MS: ai.RUNTIME_GENERATION_TIMEOUT_MS,
  RUNTIME_EMAIL_TIMEOUT_MS: ai.RUNTIME_EMAIL_TIMEOUT_MS,
  HEALTH_CHECK_CACHE_TTL_MS: ai.HEALTH_CHECK_CACHE_TTL_MS,
};
