module.exports = {
  CONFIDENCE_SUCCESS: 0.75,
  CONFIDENCE_PARTIAL: 0.5,
  CONFIDENCE_GARBAGE: 0.35,
  MAX_ROLE_CANDIDATES_WARN: 5,
  MAX_ROLE_CANDIDATES_PENALTY: 10,
  MIN_CONTENT_LENGTH: 80,
  MAX_INPUT_LENGTH: 15000,
};
