const SSE_HEARTBEAT_MS = 25_000;
const SSE_ZOMBIE_TIMEOUT_MS = 90_000;
const VERSION_REGRESSION_WARN_THRESHOLD = 3;

module.exports = {
  SSE_HEARTBEAT_MS,
  SSE_ZOMBIE_TIMEOUT_MS,
  VERSION_REGRESSION_WARN_THRESHOLD,
};
